version: '2'

services:

 frontend:
  build: ./services/frontend/
  ports:
   - "5000:5000"

 cataloguedb:
  image: mongo

 catalogue:
  build: ./services/catalogue/
  ports:
   - "5001:5001"
  environment:
   MYSQL_DB_HOST: catalogueDb
   MYSQL_DB_PASSWORD: test
  links:
   - cataloguedb

 userdb:
  image: mongo
  volumes:
   - /data/mongodb:/data/db

 user:
  build: ./services/user/
  ports:
   - "5002:5002"
  links:
   - userdb
  environment:
   MYSQL_DB_HOST: userDb
   MYSQL_DB_PASSWORD: test

 cartdb:
  image: mongo
 
 cart:
  build: ./services/cart/
  ports:
   - "5003:5003"
  environment:
   MYSQL_DB_HOST: cartDb
   MYSQL_DB_PASSWORD: test

 ordersdb:
  image: mongo
 
 orders:
  build: ./services/orders/
  ports:
   - "5004:5004"
  environment:
   MYSQL_DB_HOST: ordersDb
   MYSQL_DB_PASSWORD: test

 paymentdb:
  image: mongo
 
 payment:
  build: ./services/payment/
  ports:
   - "5005:5005"
  environment:
   MYSQL_DB_HOST: paymentDb
   MYSQL_DB_PASSWORD: test

volumes:
 userDb_data:
 cartDb_data:
 ordersDb_data:
 paymentDb_data:
